apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fps-service
  description: Faster Payment service
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: Grey
